# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{protomsg}
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Will Cannings"]
  s.date = %q{2010-10-05}
  s.default_executable = %q{protomsg}
  s.description = %q{Protocol Message Buffers for C. This gem generates C socket code for reading and writing messages described in the protomsg DSL.}
  s.email = %q{me@willcannings.com}
  s.executables = ["protomsg"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "bin/protomsg",
     "lib/protomsg.rb",
     "lib/protomsg/attribute.rb",
     "lib/protomsg/message_type.rb",
     "lib/protomsg/parser.rb",
     "lib/templates/finalisers/raw_finaliser.h",
     "lib/templates/finalisers/string_finaliser.h",
     "lib/templates/getters.h",
     "lib/templates/getters/float_getter.h",
     "lib/templates/getters/int_getter.h",
     "lib/templates/getters/raw_getter.h",
     "lib/templates/getters/string_getter.h",
     "lib/templates/header.h",
     "lib/templates/header_entries/float_header_entry.h",
     "lib/templates/header_entries/int_header_entry.h",
     "lib/templates/header_entries/raw_header_entry.h",
     "lib/templates/header_entries/string_header_entry.h",
     "lib/templates/io.h",
     "lib/templates/lengths.h",
     "lib/templates/memory.h",
     "lib/templates/message_type.h",
     "lib/templates/protomsg.h",
     "lib/templates/setters.h",
     "lib/templates/setters/float_setter.h",
     "lib/templates/setters/int_setter.h",
     "lib/templates/setters/raw_setter.h",
     "lib/templates/setters/string_setter.h"
  ]
  s.homepage = %q{http://github.com/willcannings/protomsg}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Protocol Message Buffers for C}
  s.test_files = [
    "test/helper.rb",
     "test/test_protomsg.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

